<?php

namespace App\Support;

class SpeciesSearchTerms
{
    public static array $terms = [
        'Aeolian Wall Lizard',
        'Amaral\'s Brazilian Gecko',
        'American alligator',
        'Angola blind snake',
        'Bibron\'s Blind Snake',
        'Black agama',
        'Blue Mountains Swamp-skink',
        'Boulenger\'s Centipede Snake',
        'Brazilian Anole',
        'Butler\'s Snake',
        'Caicos Geckolet',
        'Cape Flat Lizard',
        'Cape Melville Rainbow Skink',
        'Cape Range clawless gecko',
        'Capricorn Ctenotus',
        'Central Fijian Banded Iguana',
        'Central Haitian Curlytail',
        'Chesterfield skink',
        'Common Burrowing Skink',
        'Congo Two-headed Snake',
        'Curicen Tree Iguana',
        'Cyclops Emo Skink',
        'Darlington\'s Least Gecko',
        'Dotted Brown Snake',
        'Egyptian egg-eating snake',
        'Florida Worm Lizard',
        'Forest Racer',
        'Graceful Tree Iguana',
        'Hispaniolan Hog-nosed Racer',
        'Hispaniolan hopping anole',
        'Humble Anole',
        'Indonesian False Bloodsucker',
        'Intermediate Flying Gecko',
        'Key New Caledonian Gecko',
        'Liwale Two-headed Snake',
        'Longtail Whip Lizard',
        'Madras Spotted Skink',
        'Maned forest lizard',
        'Many-spotted Snake',
        'Merida Coral Snake',
        'Mindoro Anglehead',
        'Mocquard\'s Leaf-toed Gecko',
        'Montane Forest Tree Snake',
        'Montserrat Blindsnake',
        'Mount Kinabalu Pit Viper',
        'Mountain Heath Dragon',
        'Mountain Skink',
        'Ornate Green Snake',
        'Pakistani Ribbon snake',
        'Panama Teiid',
        'Pico Duarte Galliwasp',
        'Rabino\'s Tree Iguana',
        'Red-Throated Skink',
        'Rodrigues\' Day Gecko',
        'Saddle-backed sea snake',
        'Sahelian Burrowing Asp',
        'Sakishima grass lizard',
        'Santo Domingo Green Anole',
        'Sharp Anole',
        'Shield-snouted Geckolet',
        'Slender Lipinia',
        'Slevin\'s Chuckwalla',
        'Smith\'s Leaf-toed Gecko',
        'South American Clawed Gecko',
        'Southern Bluetongue',
        'Striped Grass Mabuya',
        'Swartberg Dwarf chameleon',
        'Swazi Rock Snake',
        'Tan Ground Snake',
        'Tanahjampea Cat Snake',
        'Theobald\'s Kukri Snake',
        'Tiburon Coastal Geckolet',
        'Tuberculate Toadhead Turtle',
        'Turks Island Iguana',
        'Wavy Chameleon',
        'Yellow-throated Emo Skink',
        'Ternate Dtella',
        'Nevis skink',
        'North West Cape Gehyra',
        'Laobao mangrove skink',
        'Manthey\'s Forest Dragon',
        'Sapa mabuya',
        'Scaly gecko',
        'Edel Land Slider',
        'Dame-Marie Least Gecko',
        'Cakoarita Least Gecko',
        'Dhaman',
        'Congoo gecko',
        'Anaimalais Salea',
        'Cape Flat Lizard',
        'Juventud Least Gecko',
        'Ihering\'s Fathead Anole',
        'Heath\'s Worm Lizard',
        'Panamenian Earth Snake',
        'Rhomben-Skaapsteker',
        'Wright\'s Sphenomorphus',
        'Oudeman\'s Dtella',
        'Mt. Mang Pitviper',
        'Black agama',
        'Forest Racer',
        'Humble Anole',
    ];

    public static function random(): string
    {
        return self::$terms[array_rand(self::$terms)];
    }
}
