#!/usr/bin/env python3
"""Convert a MySQL 8.4 schema dump into PostgreSQL 18 compatible DDL.

The input file is a MySQL dump produced by Laravel's ``php artisan
schema:dump`` (so it contains ``CREATE TABLE`` statements with MySQL
directives, an engine/charset footer, and a trailing block of
``INSERT INTO migrations …`` rows).

This converter:

* Strips MySQL directive comments (``/*! … */``) and character-set /
  collation noise.
* Maps MySQL column types to their PostgreSQL equivalents
  (``bigint unsigned`` → ``bigint``, ``tinyint(1)`` → ``boolean`` with
  ``0``/``1`` defaults rewritten to ``false``/``true``, ``datetime`` →
  ``timestamp``, ``longtext`` / ``mediumtext`` → ``text``, ``json`` →
  ``jsonb``, ``double(M,D)`` → ``double precision``, ``float(M,D)`` →
  ``numeric(M,D)``, ``mediumint`` → ``integer``).
* Rewrites ``AUTO_INCREMENT`` columns as
  ``GENERATED BY DEFAULT AS IDENTITY``.
* Extracts ``KEY`` / ``UNIQUE KEY`` / ``CONSTRAINT … FOREIGN KEY``
  declarations from the ``CREATE TABLE`` body.  ``KEY`` and
  ``UNIQUE KEY`` (the non-primary ones) are emitted as standalone
  ``CREATE INDEX`` / ``ALTER TABLE … ADD CONSTRAINT … UNIQUE``
  statements.  ``FOREIGN KEY`` constraints are emitted **after** every
  ``CREATE TABLE`` has run, so table order never causes a missing
  reference error.
* Rewrites ``INSERT INTO `migrations` …`` so the backticks disappear
  and appends a ``SELECT setval(…)`` so the IDENTITY sequence will not
  collide with the seeded rows.
* Wraps everything in a ``BEGIN; … COMMIT;`` transaction so a failed
  load leaves no partial schema behind.

Usage::

    python3 database/schema/convert_mysql_schema_to_postgresql.py \
        [input.sql] [output.sql]

Defaults to ``database/schema/mysql-schema.sql`` and
``database/schema/postgresql-schema.sql``.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import List, Optional, Tuple

INPUT_DEFAULT = Path("database/schema/mysql-schema.sql")
OUTPUT_DEFAULT = Path("database/schema/postgresql-schema.sql")

# ---------------------------------------------------------------------------
# File-level regexes
# ---------------------------------------------------------------------------

# /*!40101 … */;   – MySQL version-gated directives.  Stripped everywhere.
MYSQL_DIRECTIVE_RE = re.compile(r"/\*!\d+.*?\*/;?", flags=re.S)
# Bare ``SET …;`` statements that survive directive stripping (rare).
BARE_SET_RE = re.compile(r"^\s*SET\s+[^;]+;\s*$", flags=re.I)
BACKTICK_RE = re.compile(r"`")

# ---------------------------------------------------------------------------
# Statement boundaries
# ---------------------------------------------------------------------------

DROP_TABLE_RE = re.compile(
    r"^\s*DROP\s+TABLE\s+IF\s+EXISTS\s+`?(\w+)`?\s*;\s*$",
    flags=re.I,
)
CREATE_TABLE_START_RE = re.compile(
    r"^\s*CREATE\s+TABLE\s+`?(\w+)`?\s*\(\s*$",
    flags=re.I,
)
# Closing paren of a CREATE TABLE.  Anything between ``)`` and ``;`` (engine,
# charset, collate …) is dropped.
TABLE_END_RE = re.compile(r"^\s*\)[^;]*;\s*$")
INSERT_INTO_RE = re.compile(r"^\s*INSERT\s+INTO\s+`?(\w+)`?", flags=re.I)

# ---------------------------------------------------------------------------
# CREATE TABLE body parsers
# ---------------------------------------------------------------------------

PRIMARY_KEY_RE = re.compile(r"^\s*PRIMARY\s+KEY\s*\(([^)]+)\)\s*,?\s*$", flags=re.I)
UNIQUE_KEY_RE = re.compile(
    r"^\s*UNIQUE\s+KEY\s+`?(\w+)`?\s*\(([^)]+)\)\s*,?\s*$",
    flags=re.I,
)
KEY_RE = re.compile(
    r"^\s*KEY\s+`?(\w+)`?\s*\(([^)]+)\)\s*,?\s*$",
    flags=re.I,
)
CONSTRAINT_FK_RE = re.compile(
    r"^\s*CONSTRAINT\s+`?(\w+)`?\s+FOREIGN\s+KEY\s*\(([^)]+)\)"
    r"\s*REFERENCES\s+`?(\w+)`?\s*\(([^)]+)\)(.*?),?\s*$",
    flags=re.I,
)

# ---------------------------------------------------------------------------
# Type / modifier rewrites applied to a single column-definition line
# ---------------------------------------------------------------------------

CHARSET_COLLATE_RE = re.compile(
    r"\s+CHARACTER\s+SET\s+\w+|\s+COLLATE\s+\w+",
    flags=re.I,
)
AUTO_INC_RE = re.compile(r"\bNOT\s+NULL\s+AUTO_INCREMENT\b", flags=re.I)
UNSIGNED_RE = re.compile(
    r"\b(bigint|integer|int|mediumint|smallint|tinyint)\s+unsigned\b",
    flags=re.I,
)
# Catches ``unsigned`` that survives after a float/double rewrite
# (e.g. ``float(10,8) unsigned`` → ``numeric(10,8) unsigned`` → strip).
TRAILING_UNSIGNED_RE = re.compile(r"\s+unsigned\b", flags=re.I)
# ``DEFAULT '0'`` on numeric columns — PostgreSQL accepts the implicit
# cast but the canonical form is an unquoted numeric literal.
INT_DEFAULT_QUOTED_RE = re.compile(
    r"\b(bigint|integer|int|smallint|boolean|numeric|decimal|double\s+precision|real)"
    r"(\s+[^']*?DEFAULT)\s+'(-?\d+)'",
    flags=re.I,
)
TINYINT1_RE = re.compile(r"\btinyint\s*\(\s*1\s*\)", flags=re.I)
MEDIUMINT_RE = re.compile(r"\bmediumint\b", flags=re.I)
DOUBLE_PAREN_RE = re.compile(r"\bdouble\s*\(\s*\d+\s*,\s*\d+\s*\)", flags=re.I)
FLOAT_PAREN_RE = re.compile(r"\bfloat\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)", flags=re.I)
DATETIME_RE = re.compile(r"\bdatetime\b", flags=re.I)
LONGTEXT_RE = re.compile(r"\blongtext\b", flags=re.I)
MEDIUMTEXT_RE = re.compile(r"\bmediumtext\b", flags=re.I)
TINYTEXT_RE = re.compile(r"\btinytext\b", flags=re.I)
JSON_RE = re.compile(r"\bjson\b", flags=re.I)


def quote_ident(name: str) -> str:
    """Return *name* safe for use as a PostgreSQL identifier.

    Names made entirely of valid unquoted characters (and not starting with a
    digit) are returned as-is.  Everything else is double-quoted.
    """
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
        return name
    return '"' + name.replace('"', '""') + '"'


def strip_backticks(text: str) -> str:
    return BACKTICK_RE.sub("", text).strip()


def convert_column_line(line: str) -> str:
    """Translate types and modifiers on a single column definition."""
    line = BACKTICK_RE.sub("", line)
    line = CHARSET_COLLATE_RE.sub("", line)
    line = AUTO_INC_RE.sub("GENERATED BY DEFAULT AS IDENTITY", line)

    # tinyint(1) → boolean, with DEFAULT '0' / DEFAULT '1' rewritten to
    # DEFAULT false / DEFAULT true on the same line.
    if TINYINT1_RE.search(line):
        line = TINYINT1_RE.sub("boolean", line)
        line = re.sub(r"DEFAULT\s+'0'", "DEFAULT false", line, flags=re.I)
        line = re.sub(r"DEFAULT\s+'1'", "DEFAULT true", line, flags=re.I)

    # Strip ``unsigned`` from integer types (PG has no unsigned ints).
    line = UNSIGNED_RE.sub(lambda m: m.group(1).lower(), line)
    # mediumint has no direct PG equivalent.
    line = MEDIUMINT_RE.sub("integer", line)
    # double(M,D) → double precision.  MySQL's (M,D) is only a display hint.
    line = DOUBLE_PAREN_RE.sub("double precision", line)
    # float(M,D) was used as a fixed-precision decimal in the source schema
    # (for lat/lon), so preserve the precision as numeric.
    line = FLOAT_PAREN_RE.sub(lambda m: f"numeric({m.group(1)},{m.group(2)})", line)
    # datetime → timestamp (without time zone; that's PG's default).
    line = DATETIME_RE.sub("timestamp", line)
    # longtext / mediumtext / tinytext → text (PG text has no length cap).
    line = LONGTEXT_RE.sub("text", line)
    line = MEDIUMTEXT_RE.sub("text", line)
    line = TINYTEXT_RE.sub("text", line)
    # Prefer jsonb — indexable, binary storage, same API as json in Laravel.
    line = JSON_RE.sub("jsonb", line)
    # Any ``unsigned`` still sitting on the line (e.g. after ``float(M,D)``
    # → ``numeric(M,D)``) is meaningless to PostgreSQL; drop it.
    line = TRAILING_UNSIGNED_RE.sub("", line)
    # Unquote integer literals in DEFAULT clauses on numeric/boolean cols.
    line = INT_DEFAULT_QUOTED_RE.sub(r"\1\2 \3", line)

    return line.rstrip()


# ---------------------------------------------------------------------------
# Main conversion
# ---------------------------------------------------------------------------


def process(text: str) -> str:
    text = MYSQL_DIRECTIVE_RE.sub("", text)
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    lines = text.split("\n")

    table_blocks: List[str] = []  # DROP + CREATE + CREATE INDEX per table
    fk_statements: List[str] = []  # ALTER TABLE … ADD CONSTRAINT FK (deferred)
    insert_blocks: List[str] = []  # INSERT INTO migrations … etc.
    insert_tables: dict[str, List[str]] = {}  # table → raw id-bearing INSERTs

    i = 0
    while i < len(lines):
        line = lines[i]

        if not line.strip():
            i += 1
            continue

        if BARE_SET_RE.match(line):
            i += 1
            continue

        m = DROP_TABLE_RE.match(line)
        if m:
            table_blocks.append(f"DROP TABLE IF EXISTS {m.group(1)} CASCADE;")
            i += 1
            continue

        m = CREATE_TABLE_START_RE.match(line)
        if m:
            table_name = m.group(1)
            body: List[str] = []
            i += 1
            while i < len(lines) and not TABLE_END_RE.match(lines[i]):
                body.append(lines[i])
                i += 1
            # Consume the closing ``);`` (or `)ENGINE=…;`).
            if i < len(lines):
                i += 1

            rendered_create, rendered_indexes, rendered_fks = render_table(table_name, body)
            table_blocks.append(rendered_create)
            table_blocks.extend(rendered_indexes)
            table_blocks.append("")  # visual separator
            fk_statements.extend(rendered_fks)
            continue

        m = INSERT_INTO_RE.match(line)
        if m:
            cleaned = BACKTICK_RE.sub("", line).rstrip()
            insert_blocks.append(cleaned)
            insert_tables.setdefault(m.group(1), []).append(cleaned)
            i += 1
            continue

        # Anything else: keep it with backticks stripped.  Shouldn't happen
        # for well-formed input, but we don't want to silently drop data.
        kept = BACKTICK_RE.sub("", line).rstrip()
        if kept:
            table_blocks.append(kept)
        i += 1

    # Bump IDENTITY sequences past the highest id that was seeded, so the
    # next Laravel-generated row doesn't collide.
    setval_statements: List[str] = []
    for table, rows in insert_tables.items():
        max_id = _max_leading_int(rows)
        if max_id is not None:
            setval_statements.append(
                f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), {max_id});"
            )

    sections: List[str] = []
    sections.append("-- Generated by database/schema/convert_mysql_schema_to_postgresql.py")
    sections.append("-- Target: PostgreSQL 18")
    sections.append("BEGIN;")
    sections.append("\n".join(table_blocks).rstrip())
    if fk_statements:
        sections.append("-- Foreign key constraints (deferred so table order does not matter)")
        sections.append("\n".join(fk_statements))
    if insert_blocks:
        sections.append("-- Seed data")
        sections.append("\n".join(insert_blocks))
    if setval_statements:
        sections.append("-- Advance IDENTITY sequences past seeded rows")
        sections.append("\n".join(setval_statements))
    sections.append("COMMIT;")

    result = "\n\n".join(section for section in sections if section.strip())
    result = re.sub(r"\n{3,}", "\n\n", result)
    return result.rstrip() + "\n"


def render_table(
    table_name: str,
    body_lines: List[str],
) -> Tuple[str, List[str], List[str]]:
    """Render a single ``CREATE TABLE`` along with its deferred DDL.

    Returns ``(create_stmt, index_stmts, fk_stmts)``.
    """

    column_defs: List[str] = []
    pk_cols: Optional[str] = None
    uniques: List[Tuple[str, str]] = []  # (name, cols)
    indexes: List[Tuple[str, str]] = []  # (name, cols)
    fks: List[Tuple[str, str, str, str, str]] = []  # name, cols, ref, ref_cols, tail

    for body_line in body_lines:
        m = PRIMARY_KEY_RE.match(body_line)
        if m:
            pk_cols = strip_backticks(m.group(1))
            continue
        m = UNIQUE_KEY_RE.match(body_line)
        if m:
            uniques.append((m.group(1), strip_backticks(m.group(2))))
            continue
        m = CONSTRAINT_FK_RE.match(body_line)
        if m:
            tail = m.group(5).strip()
            fks.append((m.group(1), strip_backticks(m.group(2)), m.group(3),
                        strip_backticks(m.group(4)), tail))
            continue
        m = KEY_RE.match(body_line)
        if m:
            indexes.append((m.group(1), strip_backticks(m.group(2))))
            continue

        converted = convert_column_line(body_line).rstrip().rstrip(",")
        if converted.strip():
            column_defs.append(converted)

    inner: List[str] = list(column_defs)
    if pk_cols is not None:
        inner.append(f"  PRIMARY KEY ({pk_cols})")
    for uname, ucols in uniques:
        inner.append(f"  CONSTRAINT {quote_ident(uname)} UNIQUE ({ucols})")

    create_stmt = (
        f"CREATE TABLE {table_name} (\n"
        + ",\n".join(inner)
        + "\n);"
    )

    index_stmts = [
        f"CREATE INDEX {quote_ident(name)} ON {table_name} ({cols});"
        for name, cols in indexes
    ]

    fk_stmts: List[str] = []
    for name, cols, ref_table, ref_cols, tail in fks:
        tail_part = f" {tail}" if tail else ""
        fk_stmts.append(
            f"ALTER TABLE {table_name} ADD CONSTRAINT {quote_ident(name)} "
            f"FOREIGN KEY ({cols}) REFERENCES {ref_table} ({ref_cols}){tail_part};"
        )

    return create_stmt, index_stmts, fk_stmts


def _max_leading_int(insert_rows: List[str]) -> Optional[int]:
    """Return the maximum integer appearing as the first VALUES column.

    We use this to bump IDENTITY sequences past seeded rows.  Returns
    ``None`` if no row looks like it carries a leading integer id.
    """
    max_id: Optional[int] = None
    pattern = re.compile(r"VALUES\s*\(\s*(\d+)\s*,", flags=re.I)
    for row in insert_rows:
        m = pattern.search(row)
        if not m:
            continue
        value = int(m.group(1))
        if max_id is None or value > max_id:
            max_id = value
    return max_id


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main() -> int:
    input_path = Path(sys.argv[1]) if len(sys.argv) > 1 else INPUT_DEFAULT
    output_path = Path(sys.argv[2]) if len(sys.argv) > 2 else OUTPUT_DEFAULT

    if not input_path.exists():
        print(f"ERROR: input file not found: {input_path}", file=sys.stderr)
        return 2

    text = input_path.read_text(encoding="utf-8")
    result = process(text)
    output_path.write_text(result, encoding="utf-8")
    print(f"Converted schema written to: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
