#!/usr/bin/env python3
"""Convert a MySQL schema dump into PostgreSQL 18 compatible DDL."""

import re
import sys
from pathlib import Path
from typing import Optional

INPUT_DEFAULT = Path("database/schema/mysql-schema.sql")
OUTPUT_DEFAULT = Path("database/schema/postgresql-schema.sql")

MYSQL_DIRECTIVE_RE = re.compile(r"/\*!\d+ .*?\*/;?", flags=re.S)
CHARSET_COLLATE_RE = re.compile(r"\s*CHARACTER SET [^\s,()\r\n]+|\s*COLLATE [^\s,()\r\n]+", flags=re.I)
ENGINE_OPTIONS_RE = re.compile(r"\)\s*ENGINE=[^;]+;", flags=re.I)
DEFAULT_CHARSET_RE = re.compile(r"\)\s*DEFAULT CHARSET=[^;]+;", flags=re.I)
UNSIGNED_RE = re.compile(r"\b(bigint|int|mediumint|smallint|tinyint) unsigned\b", flags=re.I)
AUTO_INCREMENT_RE = re.compile(r"\bNOT NULL\s+AUTO_INCREMENT\b", flags=re.I)
DOUBLE_RE = re.compile(r"\bdouble\s*\([^)]*\)", flags=re.I)
DATETIME_RE = re.compile(r"\bdatetime\b", flags=re.I)
TINYINT1_DEFAULT_RE = re.compile(
    r"tinyint\(1\)\s+(NOT NULL\s+)?DEFAULT\s+'([01])'", flags=re.I
)
TINYINT1_RE = re.compile(r"\btinyint\(1\)\b", flags=re.I)
BACKTICK_RE = re.compile(r"`")
DROP_TABLE_RE = re.compile(r"^\s*DROP TABLE IF EXISTS\s+`?([a-zA-Z0-9_]+)`?\s*;?", flags=re.I)
CREATE_TABLE_RE = re.compile(r"^\s*CREATE TABLE\s+`?([a-zA-Z0-9_]+)`?", flags=re.I)
KEY_RE = re.compile(r"^\s*KEY\s+([a-zA-Z0-9_]+)\s*\(([^)]+)\)\s*,?\s*$", flags=re.I | re.M)
UNIQUE_KEY_RE = re.compile(r"^\s*UNIQUE\s+KEY\s+([a-zA-Z0-9_]+)\s*\(([^)]+)\)(\s*,?)\s*$", flags=re.I | re.M)


def normalize_types(line: str) -> str:
    line = BACKTICK_RE.sub("", line)
    line = MYSQL_DIRECTIVE_RE.sub("", line)
    line = CHARSET_COLLATE_RE.sub("", line)
    line = AUTO_INCREMENT_RE.sub("GENERATED BY DEFAULT AS IDENTITY", line)
    line = UNSIGNED_RE.sub(lambda m: m.group(1).lower(), line)
    line = DOUBLE_RE.sub("double precision", line)
    line = DATETIME_RE.sub("timestamp without time zone", line)

    def tiny_default(match: re.Match) -> str:
        notnull = match.group(1) or ""
        value = match.group(2)
        bool_value = "true" if value == "1" else "false"
        return f"boolean {notnull}DEFAULT {bool_value}"

    line = TINYINT1_DEFAULT_RE.sub(tiny_default, line)
    line = TINYINT1_RE.sub("boolean", line)
    line = line.replace("longtext", "text")
    line = ENGINE_OPTIONS_RE.sub(
        lambda m: ")", line
    )
    line = DEFAULT_CHARSET_RE.sub(
        lambda m: ")", line
    )
    if line.strip().upper().endswith("ENGINE=INNODB"):
        line = line[: line.upper().rfind("ENGINE=INNODB")].rstrip()
    return line


def quote_identifier(name: str) -> str:
    if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", name):
        return name
    return '"' + name.replace('"', '""') + '"'


def convert_schema(text: str) -> str:
    text = MYSQL_DIRECTIVE_RE.sub("", text)
    text = BACKTICK_RE.sub("", text)
    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")

    text = CHARSET_COLLATE_RE.sub("", text)
    text = AUTO_INCREMENT_RE.sub("GENERATED BY DEFAULT AS IDENTITY", text)
    text = UNSIGNED_RE.sub(lambda m: m.group(1).lower(), text)
    text = DOUBLE_RE.sub("double precision", text)
    text = DATETIME_RE.sub("timestamp without time zone", text)

    def tiny_default(match: re.Match) -> str:
        notnull = match.group(1) or ""
        value = match.group(2)
        bool_value = "true" if value == "1" else "false"
        return f"boolean {notnull}DEFAULT {bool_value}"

    text = TINYINT1_DEFAULT_RE.sub(tiny_default, text)
    text = TINYINT1_RE.sub("boolean", text)
    text = text.replace("longtext", "text")
    text = ENGINE_OPTIONS_RE.sub(")", text)
    text = DEFAULT_CHARSET_RE.sub(")", text)

    def unique_key_repl(match: re.Match) -> str:
        name = quote_identifier(match.group(1))
        columns = match.group(2)
        comma = match.group(3) or ""
        return f"  CONSTRAINT {name} UNIQUE ({columns}){comma}"

    text = UNIQUE_KEY_RE.sub(unique_key_repl, text)

    def key_repl(match: re.Match) -> str:
        name = quote_identifier(match.group(1))
        columns = match.group(2)
        return f"/*INDEX:{name}:{columns}*/"

    text = KEY_RE.sub(key_repl, text)

    def constraint_name_repl(match: re.Match) -> str:
        prefix = match.group(1)
        name = quote_identifier(match.group(2))
        suffix = match.group(3)
        return f"{prefix}{name}{suffix}"

    text = re.sub(
        r"(^\s*CONSTRAINT\s+)([A-Za-z0-9_]+)(\s+)",
        constraint_name_repl,
        text,
        flags=re.I | re.M,
    )
    text = re.sub(r",\s*\)\s*;", ")\n;", text)
    text = re.sub(r",\s*\)", ")", text)

    text = re.sub(r"DROP TABLE IF EXISTS\s+([a-zA-Z0-9_]+)\s*;", r"DROP TABLE IF EXISTS \1 CASCADE;", text)

    result_lines = []
    pending_indexes: list[str] = []
    current_table: Optional[str] = None
    index_placeholder_re = re.compile(r"^\s*/\*INDEX:([^:]+):([^)]+)\*/\s*$")

    for line in text.splitlines():
        create_match = CREATE_TABLE_RE.match(line)
        if create_match:
            current_table = create_match.group(1)

        placeholder_match = index_placeholder_re.match(line)
        if placeholder_match:
            index_name = placeholder_match.group(1)
            columns = placeholder_match.group(2)
            if not current_table:
                raise ValueError("Found index definition without current table")
            pending_indexes.append(
                f"CREATE INDEX {index_name} ON {current_table} ({columns});"
            )
            continue

        if line.strip() == ")":
            if result_lines and result_lines[-1].rstrip().endswith(","):
                result_lines[-1] = result_lines[-1].rstrip().rstrip(",")
            result_lines.append(");")
            if pending_indexes:
                result_lines.extend(pending_indexes)
                pending_indexes = []
            continue

        result_lines.append(line)

    return "\n".join(result_lines).strip() + "\n"
    text = MYSQL_DIRECTIVE_RE.sub("", text)
    text = BACKTICK_RE.sub("", text)
    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")
    text = text.strip("\n") + "\n"

    result_lines = []
    pending_index_statements = []
    inside_create = False
    table_name = None
    create_block_lines: list[str] = []

    for raw_line in text.splitlines():
        line = normalize_types(raw_line)
        if not inside_create:
            drop_match = DROP_TABLE_RE.match(line)
            create_match = CREATE_TABLE_RE.match(line)
            if drop_match:
                result_lines.append(f"DROP TABLE IF EXISTS {drop_match.group(1)} CASCADE;")
                continue
            if create_match:
                inside_create = True
                table_name = create_match.group(1)
                create_block_lines = [line]
                continue
            if line.strip() == "":
                continue
            result_lines.append(line)
            continue

        create_block_lines.append(line)
        if line.strip().endswith(";"):
            inside_create = False
            block_text = "\n".join(create_block_lines)
            if block_text.strip().endswith(";"):
                block_text = block_text.rstrip().rstrip(";")
            block_text = ENGINE_OPTIONS_RE.sub(")", block_text)
            block_text = DEFAULT_CHARSET_RE.sub(")", block_text)
            converted_block, indexes = convert_create_table_block(block_text, table_name)
            result_lines.append(converted_block)
            pending_index_statements.extend(indexes)
            continue

    if pending_index_statements:
        result_lines.append("")
        result_lines.extend(pending_index_statements)

    return "\n".join(result_lines).strip() + "\n"


def main() -> int:
    input_path = Path(sys.argv[1]) if len(sys.argv) > 1 else INPUT_DEFAULT
    output_path = Path(sys.argv[2]) if len(sys.argv) > 2 else OUTPUT_DEFAULT

    if not input_path.exists():
        print(f"ERROR: input file not found: {input_path}", file=sys.stderr)
        return 2

    text = input_path.read_text(encoding="utf-8")
    result = convert_schema(text)
    output_path.write_text(result, encoding="utf-8")
    print(f"Converted schema written to: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
