-- Generated by database/schema/convert_mysql_schema_to_postgresql.py

-- Target: PostgreSQL 18

BEGIN;

DROP TABLE IF EXISTS addresses CASCADE;
CREATE TABLE addresses (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  addressable_type varchar(255) NOT NULL,
  addressable_id bigint NOT NULL,
  nickname varchar(80) DEFAULT NULL,
  country varchar(255) NOT NULL,
  street_address varchar(255) NOT NULL,
  unit_number varchar(255) DEFAULT NULL,
  city varchar(255) DEFAULT NULL,
  state varchar(255) DEFAULT NULL,
  postal_code varchar(255) DEFAULT NULL,
  latitude double precision DEFAULT NULL,
  longitude double precision DEFAULT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX addresses_addressable_type_addressable_id_index ON addresses (addressable_type,addressable_id);

DROP TABLE IF EXISTS animal_morph CASCADE;
CREATE TABLE animal_morph (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  animal_id bigint NOT NULL,
  morph_id bigint NOT NULL,
  homozygous boolean NOT NULL DEFAULT false,
  proven_het boolean NOT NULL DEFAULT false,
  percent_poss_het smallint NOT NULL DEFAULT 0,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX animal_morph_animal_id_foreign ON animal_morph (animal_id);
CREATE INDEX animal_morph_morph_id_foreign ON animal_morph (morph_id);

DROP TABLE IF EXISTS animals CASCADE;
CREATE TABLE animals (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  pet_name varchar(255) NOT NULL,
  slug varchar(255) NOT NULL,
  acquisition_cost int DEFAULT NULL,
  acquisition_date date DEFAULT NULL,
  breeder_id bigint DEFAULT NULL,
  vendor_id bigint DEFAULT NULL,
  field_observation_id bigint DEFAULT NULL,
  brood_id bigint DEFAULT NULL,
  date_of_birth date DEFAULT NULL,
  description text,
  notes jsonb DEFAULT NULL,
  female boolean NOT NULL DEFAULT false,
  proven_breeder boolean NOT NULL DEFAULT false,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT animals_slug_unique UNIQUE (slug)
);
CREATE INDEX animals_breeder_id_foreign ON animals (breeder_id);
CREATE INDEX animals_brood_id_foreign ON animals (brood_id);
CREATE INDEX vendor_id ON animals (vendor_id);
CREATE INDEX field_observation_id ON animals (field_observation_id);

DROP TABLE IF EXISTS appellation_species CASCADE;
CREATE TABLE appellation_species (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  appellation_id bigint NOT NULL,
  species_id bigint NOT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX appellation_species_appellation_id_foreign ON appellation_species (appellation_id);
CREATE INDEX appellation_species_species_id_foreign ON appellation_species (species_id);

DROP TABLE IF EXISTS appellations CASCADE;
CREATE TABLE appellations (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  name varchar(255) NOT NULL,
  slug varchar(255) NOT NULL,
  description text,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT appellations_slug_unique UNIQUE (slug),
  CONSTRAINT appellations_name_unique UNIQUE (name)
);

DROP TABLE IF EXISTS articles CASCADE;
CREATE TABLE articles (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id bigint NOT NULL,
  title varchar(255) NOT NULL,
  slug varchar(255) NOT NULL,
  subtitle varchar(255) DEFAULT NULL,
  body text NOT NULL,
  custom_data jsonb NOT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT articles_title_unique UNIQUE (title),
  CONSTRAINT articles_slug_unique UNIQUE (slug)
);
CREATE INDEX articles_user_id_foreign ON articles (user_id);

DROP TABLE IF EXISTS breeders CASCADE;
CREATE TABLE breeders (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  name varchar(255) NOT NULL,
  slug varchar(255) NOT NULL,
  email varchar(140) DEFAULT NULL,
  website varchar(255) DEFAULT NULL,
  morph_market varchar(255) DEFAULT NULL,
  facebook varchar(255) DEFAULT NULL,
  instagram varchar(255) DEFAULT NULL,
  youtube varchar(255) DEFAULT NULL,
  phone varchar(255) DEFAULT NULL,
  description text,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT breeders_slug_unique UNIQUE (slug)
);

DROP TABLE IF EXISTS broods CASCADE;
CREATE TABLE broods (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  breeder_id bigint NOT NULL,
  laid_on date DEFAULT NULL,
  first_pip date DEFAULT NULL,
  born date DEFAULT NULL,
  total_eggs smallint DEFAULT NULL,
  eggs_viable smallint NOT NULL DEFAULT 0,
  viable_progeny_total smallint NOT NULL DEFAULT 0,
  viable_males smallint NOT NULL DEFAULT 0,
  viable_females smallint NOT NULL DEFAULT 0,
  viable_unsexed smallint NOT NULL DEFAULT 0,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX broods_breeder_id_foreign ON broods (breeder_id);

DROP TABLE IF EXISTS complex_morph CASCADE;
CREATE TABLE complex_morph (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  complex_id bigint NOT NULL,
  morph_id bigint NOT NULL,
  notes text,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX complex_morph_complex_id_foreign ON complex_morph (complex_id);
CREATE INDEX complex_morph_morph_id_foreign ON complex_morph (morph_id);

DROP TABLE IF EXISTS complexes CASCADE;
CREATE TABLE complexes (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  species_id bigint NOT NULL,
  name varchar(255) NOT NULL,
  description text,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX complexes_species_id_foreign ON complexes (species_id);

DROP TABLE IF EXISTS failed_jobs CASCADE;
CREATE TABLE failed_jobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  uuid varchar(255) NOT NULL,
  connection text NOT NULL,
  queue text NOT NULL,
  payload text NOT NULL,
  exception text NOT NULL,
  failed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS feedings CASCADE;
CREATE TABLE feedings (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  offered_at timestamp NOT NULL,
  food_items jsonb NOT NULL,
  refused boolean NOT NULL DEFAULT false,
  notes text,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS field_observations CASCADE;
CREATE TABLE field_observations (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  species_id bigint NOT NULL,
  title text NOT NULL,
  notes text NOT NULL,
  observed date NOT NULL,
  specific_time timestamp NOT NULL,
  latitude double precision DEFAULT NULL,
  longitude double precision DEFAULT NULL,
  collected boolean NOT NULL DEFAULT false,
  doa boolean NOT NULL DEFAULT false,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX field_observations_species_id_index ON field_observations (species_id);

DROP TABLE IF EXISTS measurements CASCADE;
CREATE TABLE measurements (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  animal_id bigint NOT NULL,
  grams bigint NOT NULL,
  height_cm int DEFAULT NULL,
  scale_rows_mid_body_cm int DEFAULT NULL,
  diameter_mid_body_cm int DEFAULT NULL,
  length_full_cm int DEFAULT NULL,
  length_svl_cm int DEFAULT NULL,
  taken_at timestamp NOT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  birth_measurement boolean NOT NULL DEFAULT false,
  PRIMARY KEY (id)
);
CREATE INDEX weights_animal_id_foreign ON measurements (animal_id);

DROP TABLE IF EXISTS media CASCADE;
CREATE TABLE media (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  url varchar(255) NOT NULL,
  mediable_type varchar(255) NOT NULL,
  mediable_id bigint NOT NULL,
  license varchar(255) DEFAULT '',
  exif jsonb DEFAULT NULL,
  copyright varchar(255) DEFAULT NULL,
  author varchar(255) DEFAULT NULL,
  latitude numeric(10,8) DEFAULT NULL,
  longitude numeric(11,8) DEFAULT NULL,
  title varchar(255) DEFAULT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX media_mediable_type_mediable_id_index ON media (mediable_type,mediable_id);

DROP TABLE IF EXISTS migrations CASCADE;
CREATE TABLE migrations (
  id int GENERATED BY DEFAULT AS IDENTITY,
  migration varchar(255) NOT NULL,
  batch int NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS morphs CASCADE;
CREATE TABLE morphs (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  species_id bigint NOT NULL,
  complex_id bigint NOT NULL,
  name varchar(255) NOT NULL DEFAULT '0',
  description text,
  recessive varchar(255) NOT NULL DEFAULT '0',
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX "1" ON morphs (species_id);
CREATE INDEX morphs_complex_id_foreign ON morphs (complex_id);

DROP TABLE IF EXISTS notes CASCADE;
CREATE TABLE notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  notable_type varchar(255) NOT NULL,
  notable_id bigint NOT NULL,
  content text NOT NULL,
  custom_data jsonb DEFAULT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX notes_notable_type_notable_id_index ON notes (notable_type,notable_id);

DROP TABLE IF EXISTS oauth_access_tokens CASCADE;
CREATE TABLE oauth_access_tokens (
  id varchar(100) NOT NULL,
  user_id bigint DEFAULT NULL,
  client_id bigint NOT NULL,
  name varchar(255) DEFAULT NULL,
  scopes text,
  revoked boolean NOT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  expires_at timestamp DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX oauth_access_tokens_user_id_index ON oauth_access_tokens (user_id);

DROP TABLE IF EXISTS oauth_auth_codes CASCADE;
CREATE TABLE oauth_auth_codes (
  id varchar(100) NOT NULL,
  user_id bigint NOT NULL,
  client_id bigint NOT NULL,
  scopes text,
  revoked boolean NOT NULL,
  expires_at timestamp DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX oauth_auth_codes_user_id_index ON oauth_auth_codes (user_id);

DROP TABLE IF EXISTS oauth_clients CASCADE;
CREATE TABLE oauth_clients (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id bigint DEFAULT NULL,
  name varchar(255) NOT NULL,
  secret varchar(100) DEFAULT NULL,
  provider varchar(255) DEFAULT NULL,
  redirect text NOT NULL,
  personal_access_client boolean NOT NULL,
  password_client boolean NOT NULL,
  revoked boolean NOT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX oauth_clients_user_id_index ON oauth_clients (user_id);

DROP TABLE IF EXISTS oauth_personal_access_clients CASCADE;
CREATE TABLE oauth_personal_access_clients (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  client_id bigint NOT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS oauth_refresh_tokens CASCADE;
CREATE TABLE oauth_refresh_tokens (
  id varchar(100) NOT NULL,
  access_token_id varchar(100) NOT NULL,
  revoked boolean NOT NULL,
  expires_at timestamp DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX oauth_refresh_tokens_access_token_id_index ON oauth_refresh_tokens (access_token_id);

DROP TABLE IF EXISTS pairings CASCADE;
CREATE TABLE pairings (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  dam_id bigint NOT NULL,
  sire_id bigint NOT NULL,
  introduced_on_date date DEFAULT NULL,
  observed boolean NOT NULL DEFAULT false,
  observed_on_date date DEFAULT NULL,
  separated_on_date date DEFAULT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX pairings_dam_id_foreign ON pairings (dam_id);
CREATE INDEX pairings_sire_id_foreign ON pairings (sire_id);

DROP TABLE IF EXISTS password_reset_tokens CASCADE;
CREATE TABLE password_reset_tokens (
  email varchar(255) NOT NULL,
  token varchar(255) NOT NULL,
  created_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (email)
);

DROP TABLE IF EXISTS password_resets CASCADE;
CREATE TABLE password_resets (
  email varchar(255) NOT NULL,
  token varchar(255) NOT NULL,
  created_at timestamp NULL DEFAULT NULL
);
CREATE INDEX password_resets_email_index ON password_resets (email);

DROP TABLE IF EXISTS personal_access_tokens CASCADE;
CREATE TABLE personal_access_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tokenable_type varchar(255) NOT NULL,
  tokenable_id bigint NOT NULL,
  name varchar(255) NOT NULL,
  token varchar(64) NOT NULL,
  abilities text,
  last_used_at timestamp NULL DEFAULT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT personal_access_tokens_token_unique UNIQUE (token)
);
CREATE INDEX personal_access_tokens_tokenable_type_tokenable_id_index ON personal_access_tokens (tokenable_type,tokenable_id);

DROP TABLE IF EXISTS sellers CASCADE;
CREATE TABLE sellers (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  name varchar(255) NOT NULL,
  slug varchar(255) NOT NULL DEFAULT '',
  email varchar(140) DEFAULT NULL,
  website varchar(255) DEFAULT NULL,
  instagram varchar(255) DEFAULT NULL,
  morph_market varchar(255) DEFAULT NULL,
  created_at timestamp NULL DEFAULT NULL,
  description text,
  phone varchar(255) DEFAULT NULL,
  youtube varchar(255) DEFAULT NULL,
  facebook varchar(255) DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT vendors_name_unique UNIQUE (name),
  CONSTRAINT vendors_slug_unique UNIQUE (slug)
);

DROP TABLE IF EXISTS sessions CASCADE;
CREATE TABLE sessions (
  id varchar(255) NOT NULL,
  user_id bigint DEFAULT NULL,
  ip_address varchar(45) DEFAULT NULL,
  user_agent text,
  payload text NOT NULL,
  last_activity int NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX sessions_user_id_index ON sessions (user_id);
CREATE INDEX sessions_last_activity_index ON sessions (last_activity);

DROP TABLE IF EXISTS species CASCADE;
CREATE TABLE species (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  type_species boolean NOT NULL DEFAULT false,
  species varchar(255) NOT NULL DEFAULT '',
  author varchar(255) DEFAULT NULL,
  subspecies text,
  common_name text,
  higher_taxa varchar(255) DEFAULT NULL,
  species_number varchar(255) DEFAULT NULL,
  changes varchar(255) DEFAULT NULL,
  description text,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  name varchar(255) NOT NULL,
  email varchar(255) NOT NULL,
  email_verified_at timestamp NULL DEFAULT NULL,
  password varchar(255) NOT NULL,
  two_factor_secret text,
  two_factor_recovery_codes text,
  remember_token varchar(100) DEFAULT NULL,
  profile_photo_path text,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT users_email_unique UNIQUE (email)
);

DROP TABLE IF EXISTS vet_visits CASCADE;
CREATE TABLE vet_visits (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  animal_id bigint NOT NULL,
  veterinarian_id bigint NOT NULL,
  cost integer NOT NULL,
  date_of_visit date NOT NULL,
  reason_for_visit varchar(255) NOT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX vet_visits_animal_id_index ON vet_visits (animal_id);
CREATE INDEX vet_visits_veterinarian_id_index ON vet_visits (veterinarian_id);

DROP TABLE IF EXISTS veterinarians CASCADE;
CREATE TABLE veterinarians (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  doctor_name varchar(255) NOT NULL,
  clinic_name varchar(255) DEFAULT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
);

-- Foreign key constraints (deferred so table order does not matter)

ALTER TABLE animal_morph ADD CONSTRAINT animal_morph_animal_id_foreign FOREIGN KEY (animal_id) REFERENCES animals (id);
ALTER TABLE animal_morph ADD CONSTRAINT animal_morph_morph_id_foreign FOREIGN KEY (morph_id) REFERENCES morphs (id);
ALTER TABLE animals ADD CONSTRAINT animals_breeder_id_foreign FOREIGN KEY (breeder_id) REFERENCES breeders (id);
ALTER TABLE animals ADD CONSTRAINT animals_brood_id_foreign FOREIGN KEY (brood_id) REFERENCES broods (id);
ALTER TABLE appellation_species ADD CONSTRAINT appellation_species_appellation_id_foreign FOREIGN KEY (appellation_id) REFERENCES appellations (id);
ALTER TABLE appellation_species ADD CONSTRAINT appellation_species_species_id_foreign FOREIGN KEY (species_id) REFERENCES species (id);
ALTER TABLE articles ADD CONSTRAINT articles_user_id_foreign FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE broods ADD CONSTRAINT broods_breeder_id_foreign FOREIGN KEY (breeder_id) REFERENCES breeders (id);
ALTER TABLE complex_morph ADD CONSTRAINT complex_morph_complex_id_foreign FOREIGN KEY (complex_id) REFERENCES complexes (id);
ALTER TABLE complex_morph ADD CONSTRAINT complex_morph_morph_id_foreign FOREIGN KEY (morph_id) REFERENCES morphs (id);
ALTER TABLE complexes ADD CONSTRAINT complexes_species_id_foreign FOREIGN KEY (species_id) REFERENCES species (id);
ALTER TABLE measurements ADD CONSTRAINT weights_animal_id_foreign FOREIGN KEY (animal_id) REFERENCES animals (id);
ALTER TABLE morphs ADD CONSTRAINT "1" FOREIGN KEY (species_id) REFERENCES species (id);
ALTER TABLE morphs ADD CONSTRAINT morphs_complex_id_foreign FOREIGN KEY (complex_id) REFERENCES complexes (id);
ALTER TABLE pairings ADD CONSTRAINT pairings_dam_id_foreign FOREIGN KEY (dam_id) REFERENCES animals (id);
ALTER TABLE pairings ADD CONSTRAINT pairings_sire_id_foreign FOREIGN KEY (sire_id) REFERENCES animals (id);

-- Seed data

INSERT INTO migrations (id, migration, batch) VALUES (1,'2014_10_12_000000_create_users_table',1);
INSERT INTO migrations (id, migration, batch) VALUES (2,'2014_10_12_100000_create_password_resets_table',1);
INSERT INTO migrations (id, migration, batch) VALUES (3,'2014_10_12_200000_add_two_factor_columns_to_users_table',1);
INSERT INTO migrations (id, migration, batch) VALUES (4,'2019_08_19_000000_create_failed_jobs_table',1);
INSERT INTO migrations (id, migration, batch) VALUES (5,'2019_12_14_000001_create_personal_access_tokens_table',1);
INSERT INTO migrations (id, migration, batch) VALUES (6,'2020_05_21_100000_create_teams_table',1);
INSERT INTO migrations (id, migration, batch) VALUES (7,'2020_05_21_200000_create_team_user_table',1);
INSERT INTO migrations (id, migration, batch) VALUES (8,'2020_05_21_300000_create_team_invitations_table',1);
INSERT INTO migrations (id, migration, batch) VALUES (9,'2021_04_20_183807_create_sessions_table',1);
INSERT INTO migrations (id, migration, batch) VALUES (10,'2021_04_30_000930_create_breeders_table',1);
INSERT INTO migrations (id, migration, batch) VALUES (11,'2021_04_30_000931_create_broods_table',1);
INSERT INTO migrations (id, migration, batch) VALUES (12,'2021_04_30_000932_create_genera_table',1);
INSERT INTO migrations (id, migration, batch) VALUES (13,'2021_04_30_000932_create_species_table',1);
INSERT INTO migrations (id, migration, batch) VALUES (14,'2021_04_30_000933_create_complexes_table',1);
INSERT INTO migrations (id, migration, batch) VALUES (15,'2021_04_30_000939_create_animals_table',1);
INSERT INTO migrations (id, migration, batch) VALUES (16,'2021_04_30_000940_create_pairings_table',1);
INSERT INTO migrations (id, migration, batch) VALUES (17,'2021_04_30_001844_create_morphs_table',1);
INSERT INTO migrations (id, migration, batch) VALUES (18,'2021_04_30_004123_create_images_table',1);
INSERT INTO migrations (id, migration, batch) VALUES (19,'2021_04_30_010742_create_animal_morph_table',1);
INSERT INTO migrations (id, migration, batch) VALUES (20,'2021_04_30_014413_create_addresses_table',1);
INSERT INTO migrations (id, migration, batch) VALUES (21,'2021_04_30_033846_create_complex_morph_table',1);
INSERT INTO migrations (id, migration, batch) VALUES (22,'2021_04_30_134459_create_feedings_table',1);
INSERT INTO migrations (id, migration, batch) VALUES (23,'2021_04_30_144135_create_weights_table',2);
INSERT INTO migrations (id, migration, batch) VALUES (24,'2021_04_30_150553_create_appellations_table',2);
INSERT INTO migrations (id, migration, batch) VALUES (25,'2021_04_30_151125_create_lengths_table',2);
INSERT INTO migrations (id, migration, batch) VALUES (26,'2021_04_30_152407_modify_animals_table',3);
INSERT INTO migrations (id, migration, batch) VALUES (27,'2021_04_30_182436_create_articles_table',4);
INSERT INTO migrations (id, migration, batch) VALUES (28,'2021_04_30_201941_modify_appellations_table',5);
INSERT INTO migrations (id, migration, batch) VALUES (29,'2021_04_30_202550_create_appellation_species_table',5);
INSERT INTO migrations (id, migration, batch) VALUES (30,'2021_04_30_221604_create_shipment_table',6);
INSERT INTO migrations (id, migration, batch) VALUES (31,'2021_05_01_030510_create_vendors_table',7);
INSERT INTO migrations (id, migration, batch) VALUES (32,'2021_05_01_031233_modify_animals_table',7);
INSERT INTO migrations (id, migration, batch) VALUES (35,'2021_05_21_015200_create_field_observations_table',8);
INSERT INTO migrations (id, migration, batch) VALUES (36,'2021_05_21_015213_modify_animals_table',9);
INSERT INTO migrations (id, migration, batch) VALUES (38,'2021_05_21_181701_modify_field_observations_table',10);
INSERT INTO migrations (id, migration, batch) VALUES (39,'2021_05_21_182710_modify_animals',10);
INSERT INTO migrations (id, migration, batch) VALUES (40,'2021_05_21_232510_create_notes_table',11);
INSERT INTO migrations (id, migration, batch) VALUES (41,'2021_06_07_160438_create_vet_visits_table',12);
INSERT INTO migrations (id, migration, batch) VALUES (42,'2014_10_12_100000_create_password_reset_tokens_table',13);
INSERT INTO migrations (id, migration, batch) VALUES (43,'2023_09_16_151038_rename_vendor_table_to_seller',13);
INSERT INTO migrations (id, migration, batch) VALUES (44,'2023_09_17_114828_rename_image_table_to_media',13);
INSERT INTO migrations (id, migration, batch) VALUES (45,'2023_09_17_114952_delete_genera_table',13);
INSERT INTO migrations (id, migration, batch) VALUES (46,'2023_09_17_115024_rename_weights_table_to_measurements',13);
INSERT INTO migrations (id, migration, batch) VALUES (47,'2023_09_17_115647_drop_lengths_table',13);
INSERT INTO migrations (id, migration, batch) VALUES (48,'2023_09_17_121006_add_fields_to_measurements_table',13);
INSERT INTO migrations (id, migration, batch) VALUES (49,'2016_06_01_000001_create_oauth_auth_codes_table',14);
INSERT INTO migrations (id, migration, batch) VALUES (50,'2016_06_01_000002_create_oauth_access_tokens_table',14);
INSERT INTO migrations (id, migration, batch) VALUES (51,'2016_06_01_000003_create_oauth_refresh_tokens_table',14);
INSERT INTO migrations (id, migration, batch) VALUES (52,'2016_06_01_000004_create_oauth_clients_table',14);
INSERT INTO migrations (id, migration, batch) VALUES (53,'2016_06_01_000005_create_oauth_personal_access_clients_table',14);
INSERT INTO migrations (id, migration, batch) VALUES (54,'2023_09_17_181126_drop_complexes_table',14);
INSERT INTO migrations (id, migration, batch) VALUES (55,'2023_09_17_181127_drop_complex_morph_table',14);
INSERT INTO migrations (id, migration, batch) VALUES (56,'2023_09_17_181835_rename_images_table',15);
INSERT INTO migrations (id, migration, batch) VALUES (57,'2023_09_17_181847_rename_vendors_table',15);

-- Advance IDENTITY sequences past seeded rows

SELECT setval(pg_get_serial_sequence('migrations', 'id'), 57);

COMMIT;
